"""add assigned_by to tasks

Revision ID: 3e13d46080b8
Revises: c3d8e81feaf4
Create Date: 2025-07-02 16:20:59.007056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e13d46080b8'
down_revision: Union[str, Sequence[str], None] = 'c3d8e81feaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'assigned_by')
    # ### end Alembic commands ###
