"""Add teId to User

Revision ID: a00d81ed2ca3
Revises: 
Create Date: 2025-06-26 00:21:15.276154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00d81ed2ca3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teId', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_teId'), 'users', ['teId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_teId'), table_name='users')
    op.drop_column('users', 'teId')
    # ### end Alembic commands ###
