"""Added phone - position - joining_date - skills to users database

Revision ID: d7171c146087
Revises: cb3a129f3702
Create Date: 2025-06-27 20:36:54.315848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7171c146087'
down_revision: Union[str, Sequence[str], None] = 'cb3a129f3702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skills')
    op.drop_column('users', 'joining_date')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
