"""Add face recognition fields to users table

Revision ID: f9f215494517
Revises: 74120b278902
Create Date: 2025-08-13 03:49:18.544887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f215494517'
down_revision: Union[str, Sequence[str], None] = '74120b278902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_encoding', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('face_recognition_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_face_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_face_login')
    op.drop_column('users', 'face_recognition_enabled')
    op.drop_column('users', 'face_encoding')
    # ### end Alembic commands ###
